// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwtqwdweawxglcdewvnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3dHF3ZHdlYXd4Z2xjZGV3dm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MjQxOTUsImV4cCI6MjA3NjQwMDE5NX0.hOEpbRaQtjm4dP1gYQsKQ_vNV85cbeLb0xq5pZ_nWbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});